server {
    server_name gymdate.in www.gymdate.in;

    client_max_body_size 50M;

    location /uploads/ {
        alias /var/www/gymdate_uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/gymdate.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gymdate.in/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.gymdate.in) {
        return 301 https://$host$request_uri;
    }
    if ($host = gymdate.in) {
        return 301 https://$host$request_uri;
    }
    server_name gymdate.in www.gymdate.in;
    listen 80;
    return 404;
}
